void animationSquare(int cycles)
{
    double c=1.0;
    while (cycles)
    {
     printf("         \n");
     printf("         \n");
     printf("         \n");
     printf("         \n");
     printf("    #    \n");
     printf("         \n");
     printf("         \n");
     printf("         \n");
     printf("         \n");
     universalSleep (c);
     universalClear();
     printf("         \n");
     printf("         \n");
     printf("         \n");
     printf("   ###   \n");
     printf("   ###   \n");
     printf("   ###   \n");
     printf("         \n");
     printf("         \n");
     printf("         \n");
     universalSleep (c);
     universalClear();
     printf("         \n");
     printf("         \n");
     printf("  #####  \n");
     printf("  #####  \n");
     printf("  #####  \n");
     printf("  #####  \n");
     printf("  #####  \n");
     printf("         \n");
     printf("         \n");
     universalSleep (c);
     universalClear();
     printf("         \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf("         \n");
     universalSleep (c);
     universalClear();
     printf("#########\n");
     printf("#########\n");
     printf("#########\n");
     printf("#########\n");
     printf("#########\n");
     printf("#########\n");
     printf("#########\n");
     printf("#########\n");
     printf("#########\n");
     universalSleep (c);
     universalClear();
     printf("         \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf(" ####### \n");
     printf("         \n");
     universalSleep (c);
     universalClear();
     printf("         \n");
     printf("         \n");
     printf("  #####  \n");
     printf("  #####  \n");
     printf("  #####  \n");
     printf("  #####  \n");
     printf("  #####  \n");
     printf("         \n");
     printf("         \n");
     universalSleep (c);
     universalClear();
     printf("         \n");
     printf("         \n");
     printf("         \n");
     printf("   ###   \n");
     printf("   ###   \n");
     printf("   ###   \n");
     printf("         \n");
     printf("         \n");
     printf("         \n");
     universalSleep (c);
     universalClear();
     --cycles;
   }
}
